### ISSUE TITLE
about d7v1 

### ISSUE THREAD

**Issue by long123524** [Akhilesh64/ResUnet-a#2]
![image](https://user-images.githubusercontent.com/73996375/161408883-c8d9ce23-c1e1-49d2-927f-e9bb818ee157.png)
Hello, I tried to conduct d7v1 model but there is error, how should I modify? thank you!

**Comment by Akhilesh64** [comment]
Hi @long123524, the paper is not clear about the d7v1 model, so I commented out this part. Please use the d6 or d7v2 variants of the models as they too achieve similar accuracy as d7v1 model.
