### ISSUE TITLE
Want to know the python version u r using for tensorflow GPU  to run this code

### ISSUE THREAD

**Issue by lalan143abhishek** [Akhilesh64/ResUnet-a#6]
I am facing an error while using tensorflow-gpu==2.0.0 , It is asking for downgrading the python version. 

Please let me know the python version you have used for Tensorflow gpu.

**Comment by Akhilesh64** [comment]
Check this [link](https://www.tensorflow.org/install/source#gpu) for checking versions compatible with tensorflow-gpu.
